### ISSUE TITLE
Error: A JNI error has occurred

### ISSUE THREAD

**Issue by devendra2689** [clarkkev/deep-coref#11]
Can you please help, we are getting below mention error
```
~/softwares/CoreNLP-master$ java -Xmx2g -cp "stanford-corenlp.jar:stanford-corenlp-models-3.7.0.jar:*" edu.stanford.nlp.coref.neural.NeuralCorefDataExporter coref.properties “/home/development/devendra/deep-coref-master/output”
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: javax/json/JsonValue
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: javax.json.JsonValue
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```
This is the text from properties file
```
coref.algorithm = neural
coref.conll = true

coref.data = /home/devendra/Downloads/Internship+MTP/MTP_Stage_II/deep-coref-master/gold_conll/
coref.conllOutputPath = /home/devendra/Downloads/Internship+MTP/MTP_Stage_II/deep-coref-master/output/

```

**Comment by devendra2689** [comment]
Solved

**Comment by Achint08** [comment]
How did you solve this?

**Comment by ozturkoktay** [comment]
@devendra2689 How did you solve?
