### ISSUE TITLE
error Attempted to fetch annotator "parse" but the annotator pool does not store any such type!

### ISSUE THREAD

**Issue by xusong123** [clarkkev/deep-coref#8]
Hello, I am studying the paper "Deep Reinforcement Learning for Mention-Ranking Coference Models" and follow the steps to train my own model. But in the third step(Run the NeuralCorefDataExporter class in the development version of Stanford's CoreNLP), I occur this error. I cannot find a solution in Google. Thank you!

This is my neural-english-conll.properties:
      coref.algorithm = neural
      coref.conll = true
      coref.data = /home/hengru/deep-coref/conll-2012
      coref.conllOutputPath = /home/hengru/deep-coref/data/data_out
       coref.scorer = /home/hengru/deep-coref/data/scorer

This is the error:
hengru@dc6:~/CoreNLP/target$ java -Xmx2g -cp javax.json.jar:stanford-corenlp-3.7.0.jar:stanford-corenlp-models-3.7.0.jar:* edu.stanford.nlp.coref.neural.NeuralCorefDataExporter neural-english-conll.properties /home/hengru/deep-coref/data/data_out/
Jul 25, 2017 6:52:56 PM edu.stanford.nlp.coref.docreader.CoNLLDocumentReader <init>
INFO: Reading 1940 CoNLL files from /home/hengru/deep-coref/conll-2012/v4/data/train/data/english/annotations/
Adding annotator lemma
Adding annotator mention
Using mention detector type: rule
Attempted to fetch annotator "parse" but the annotator pool does not store any such type!
Exception in thread "main" java.lang.NullPointerException
        at edu.stanford.nlp.coref.md.CorefMentionFinder.parse(CorefMentionFinder.java:646)
        at edu.stanford.nlp.coref.md.CorefMentionFinder.findSyntacticHead(CorefMentionFinder.java:536)
        at edu.stanford.nlp.coref.md.CorefMentionFinder.findHead(CorefMentionFinder.java:456)
        at edu.stanford.nlp.coref.md.RuleBasedCorefMentionFinder.findMentions(RuleBasedCorefMentionFinder.java:100)
        at edu.stanford.nlp.pipeline.MentionAnnotator.annotate(MentionAnnotator.java:102)
        at edu.stanford.nlp.pipeline.AnnotationPipeline.annotate(AnnotationPipeline.java:76)
        at edu.stanford.nlp.pipeline.StanfordCoreNLP.annotate(StanfordCoreNLP.java:648)
        at edu.stanford.nlp.coref.data.DocumentMaker.nextDoc(DocumentMaker.java:145)
        at edu.stanford.nlp.coref.CorefDocumentProcessor.run(CorefDocumentProcessor.java:40)
        at edu.stanford.nlp.coref.CorefDocumentProcessor.run(CorefDocumentProcessor.java:25)
        at edu.stanford.nlp.coref.neural.NeuralCorefDataExporter.exportData(NeuralCorefDataExporter.java:182)
        at edu.stanford.nlp.coref.neural.NeuralCorefDataExporter.main(NeuralCorefDataExporter.java:189)

**Comment by agilajah** [comment]
Hello, did you find a workaround? I encountered a similar error.
